import * as passwordHash from 'password-hash';
import { ForecastItem } from '../../types/tmdb-types';
let forecast: ForecastItem[] = []
export const seedData = {
  users: {
    _model: "User",
    homer: {
      firstName: "Homer",
      lastName: "Simpson",
      email: "homer@simpson.com",
      password: passwordHash.generate("secret"),
    },
    marge: {
      firstName: "Marge",
      lastName: "Simpson",
      email: "marge@simpson.com",
      password: passwordHash.generate("secret"),
    },
    bart: {
      firstName: "Bart",
      lastName: "Simpson",
      email: "bart@simpson.com",
      password: passwordHash.generate("secret"),
    },
  },
  placemarks: {
    _model: "PlaceMark",
    placemark1: {
      name: "The Elysian",
      city: "Cork",
      country: "Ireland",
      user: "->users.bart",
      lat: 51.896676,
      lng: -8.463367,
      weather: "Rain",
      tempC: 10,
      tempF: 50,
      min_temp: 5,
      max_temp: 12,
      wind_spd: 4,
      wind_direction_deg: 0,
      wind_direction_txt: "N",
      humidity: 90,
      img: [],
      forecast: forecast
      }, 
    placemark2: {
      name: "Empire State Building",
      city: "New York",
      country: "United States of America",
      user: "->users.marge",
      lat: 40.74844,
      lng: -73.98566,
      weather: "Rain",
      tempC: 10,
      tempF: 50,
      min_temp: 5,
      max_temp: 12,
      wind_spd: 4,
      wind_direction_deg: 0,
      wind_direction_txt: "N",
      humidity: 90,
      img: [],
      forecast: forecast
      }, 
    placemark3: {
      name: "Burj Khalifa",
      city: "Dubai",
      country: "United Arab Emirates",
      user: "->users.homer",
      lat: 25.19703,
      lng: 55.27413,
      weather: "Sunny",
      tempC: 10,
      tempF: 50,
      min_temp: 5,
      max_temp: 12,
      wind_spd: 4,
      wind_direction_deg: 0,
      wind_direction_txt: "N",
      humidity: 90,
      img: [] ,
      forecast: forecast
    }, 
  },
  info: {
    _model: "Info",
    one: {
      category: "Building",
      desc: "Tallest Building in Ireland",
      visits: 4,
      placemark: "->placemarks.placemark1",
      user: "->users.bart",
    },
    two: {
      category: "Building",
      desc: "Previously Tallest Building in the World",
      visits: 1,
      placemark: "->placemarks.placemark2",
      user: "->users.marge",
    },
    three: {
      category: "Building",
      desc: "Current Tallest Building in the World",
      visits: 1,
      placemark: "->placemarks.placemark3",
      user: "->users.homer",
    },
  },
};